export const vocabData = [
            { kanji: "駐", vietnamese: "TRÚ", reading: "ちゅう", meaning: "" },
            { kanji: "駐車", vietnamese: "TRÚ XA", reading: "ちゅうしゃ", meaning: "Đỗ xe" },
            { kanji: "駐車場", vietnamese: "TRÚ XA TRƯỜNG", reading: "ちゅうしゃじょう", meaning: "Bãi đỗ xe" },
            { kanji: "無", vietnamese: "VÔ", reading: "む/ない", meaning: "" },
            { kanji: "無休", vietnamese: "VÔ HƯU", reading: "むきゅう", meaning: "Làm việc không có ngày nghỉ" },
            { kanji: "無料", vietnamese: "VÔ LIỆU", reading: "むりょう", meaning: "Không mất tiền phí" },
            { kanji: "無理", vietnamese: "VÔ LÝ", reading: "むり", meaning: "Vô lý, quá sức" },
            { kanji: "無い", vietnamese: "VÔ", reading: "ない", meaning: "Không có" },
            { kanji: "満", vietnamese: "MÃN", reading: "まん", meaning: "" },
            { kanji: "満車", vietnamese: "MÃN XA", reading: "まんしゃ", meaning: "Đầy xe" },
            { kanji: "満員", vietnamese: "MÃN VIÊN", reading: "まんいん", meaning: "Đầy người" },
            { kanji: "不満", vietnamese: "BẤT MÃN", reading: "ふまん", meaning: "Bất mãn" },
            { kanji: "向", vietnamese: "HƯỚNG", reading: "こう/むこう/むかう/むき", meaning: "" },
            { kanji: "方向", vietnamese: "PHƯƠNG HƯỚNG", reading: "ほうこう", meaning: "Phương hướng" },
            { kanji: "向こう", vietnamese: "HƯỚNG", reading: "むこう", meaning: "Phía bên kia" },
            { kanji: "向かう", vietnamese: "HƯỚNG", reading: "むかう", meaning: "Hướng về" },
            { kanji: "○○向き", vietnamese: "HƯỚNG", reading: "むき", meaning: "Phù hợp, dành cho + danh từ" },
            { kanji: "禁", vietnamese: "CẤM", reading: "きん", meaning: "" },
            { kanji: "禁止", vietnamese: "CẤM CHỈ", reading: "きんし", meaning: "Cấm" },
            { kanji: "関", vietnamese: "QUAN", reading: "かん", meaning: "" },
            { kanji: "関心", vietnamese: "QUAN TÂM", reading: "かんしん", meaning: "Quan tâm" },
            { kanji: "関する", vietnamese: "QUAN", reading: "かんする", meaning: "Có liên quan" },
            { kanji: "係", vietnamese: "HỆ", reading: "けい/かかり", meaning: "" },
            { kanji: "関係", vietnamese: "QUAN HỆ", reading: "かんけい", meaning: "Quan hệ" },
            { kanji: "係", vietnamese: "HỆ", reading: "かかり", meaning: "Người chịu trách nhiệm" },
            { kanji: "断", vietnamese: "ĐOẠN", reading: "だん/ことわる", meaning: "" },
            { kanji: "無断", vietnamese: "VÔ ĐOẠN", reading: "むだん", meaning: "Tự ý, không có sự cho phép" },
            { kanji: "断水", vietnamese: "ĐOẠN THỦY", reading: "だんすい", meaning: "Cắt nguồn nước" },
            { kanji: "断る", vietnamese: "ĐOẠN", reading: "ことわる", meaning: "Từ chối" },
            { kanji: "横", vietnamese: "HOÀNH", reading: "おう/よこ", meaning: "" },
            { kanji: "横断", vietnamese: "HOÀNH ĐOẠN", reading: "おうだん", meaning: "Qua đường, băng qua" },
            { kanji: "横断歩道", vietnamese: "HOÀNH ĐOẠN BỘ ĐẠO", reading: "おうだんほどう", meaning: "Đường dành cho người đi bộ" },
            { kanji: "押", vietnamese: "ÁP", reading: "おす/おさえる", meaning: "" },
            { kanji: "押す", vietnamese: "ÁP", reading: "おす", meaning: "Ấn (nút)" },
            { kanji: "押さえる", vietnamese: "ÁP", reading: "おさえる", meaning: "Ấn và giữ xuống" },
            { kanji: "押し入れ", vietnamese: "ÁP NHẬP", reading: "おしいれ", meaning: "Tủ âm" },
            { kanji: "式", vietnamese: "THỨC", reading: "しき", meaning: "" },
            { kanji: "押しボタン式", vietnamese: "ÁP THỨC", reading: "おしぼたんしき", meaning: "Nút ấn xuống (thường ở cột tín hiệu)" },
            { kanji: "入学式", vietnamese: "NHẬP HỌC THỨC", reading: "にゅうがくしき", meaning: "Lễ nhập học" },
            { kanji: "数式", vietnamese: "SỐ THỨC", reading: "すうしき", meaning: "Dãy số, công thức số" },
            { kanji: "信", vietnamese: "TÍN/TIN", reading: "しん", meaning: "" },
            { kanji: "送信", vietnamese: "TỐNG TIN", reading: "そうしん", meaning: "Đưa tin" },
            { kanji: "信じる", vietnamese: "TÍN", reading: "しんじる", meaning: "Tin tưởng" },
            { kanji: "自信", vietnamese: "TỰ TIN", reading: "じしん", meaning: "Tự tin" },
            { kanji: "信用", vietnamese: "TÍN DỤNG", reading: "しんよう", meaning: "Sự tín nhiệm" },
            { kanji: "号", vietnamese: "HIỆU", reading: "ごう", meaning: "" },
            { kanji: "信号", vietnamese: "TÍN HIỆU", reading: "しんごう", meaning: "Tín hiệu" },
            { kanji: "~号車", vietnamese: "HIỆU XA", reading: "ごうしゃ", meaning: "Xe số..." },
            { kanji: "確", vietnamese: "XÁC", reading: "かく/たしか/たしかめる", meaning: "" },
            { kanji: "正確", vietnamese: "CHÍNH XÁC", reading: "せいかく", meaning: "Chính xác" },
            { kanji: "確かめる", vietnamese: "XÁC", reading: "たしかめる", meaning: "Xác nhận" },
            { kanji: "確か", vietnamese: "XÁC", reading: "たしか", meaning: "Chắc là, quả thật là" },
            { kanji: "認", vietnamese: "NHẬN", reading: "にん/みとめる", meaning: "" },
            { kanji: "確認", vietnamese: "XÁC NHẬN", reading: "かくにん", meaning: "Xác nhận" },
            { kanji: "認める", vietnamese: "NHẬN", reading: "みとめる", meaning: "Chấp nhận, thừa nhận" },
            { kanji: "飛", vietnamese: "PHI", reading: "ひ/とぶ", meaning: "" },
            { kanji: "飛行場", vietnamese: "PHI HÀNH TRƯỜNG", reading: "ひこうじょう", meaning: "Sân bay" },
            { kanji: "飛ぶ", vietnamese: "PHI", reading: "とぶ", meaning: "Bay" },
            { kanji: "非", vietnamese: "PHI", reading: "ひ", meaning: "" },
            { kanji: "非常", vietnamese: "PHI THƯỜNG", reading: "ひじょう", meaning: "Khẩn cấp" },
            { kanji: "非常に", vietnamese: "PHI THƯỜNG", reading: "ひじょうに", meaning: "Rất, đặc biệt..." },
            { kanji: "非常口", vietnamese: "PHI THƯỜNG KHẨU", reading: "ひじょうぐち", meaning: "Lối thoát hiểm" },
            { kanji: "常", vietnamese: "THƯỜNG", reading: "じょう", meaning: "" },
            { kanji: "日常", vietnamese: "NHẬT THƯỜNG", reading: "にちじょう", meaning: "Thường ngày" },
            { kanji: "正常", vietnamese: "CHÍNH THƯỜNG", reading: "せいじょう", meaning: "Bình thường, formal" },
            { kanji: "階", vietnamese: "GIAI", reading: "かい", meaning: "" },
            { kanji: "~階", vietnamese: "GIAI", reading: "かい", meaning: "Tầng (mấy)" },
            { kanji: "段", vietnamese: "ĐOẠN", reading: "だん", meaning: "" },
            { kanji: "階段", vietnamese: "GIAI ĐOẠN", reading: "かいだん", meaning: "Cầu thang" },
            { kanji: "箱", vietnamese: "TƯƠNG", reading: "はこ", meaning: "" },
            { kanji: "箱", vietnamese: "TƯƠNG", reading: "はこ", meaning: "Hộp" },
            { kanji: "ごみ箱", vietnamese: "TƯƠNG", reading: "ごみばこ", meaning: "Thùng rác" },
            { kanji: "危", vietnamese: "NGUY", reading: "き/あぶない", meaning: "" },
            { kanji: "危険", vietnamese: "NGUY HIỂM", reading: "きけん", meaning: "Nguy hiểm" },
            { kanji: "危ない", vietnamese: "NGUY", reading: "あぶない", meaning: "Nguy hiểm" },
            { kanji: "険", vietnamese: "HIỂM", reading: "けん", meaning: "" },
            { kanji: "捨", vietnamese: "XẢ", reading: "すてる", meaning: "" },
            { kanji: "捨てる", vietnamese: "XẢ", reading: "すてる", meaning: "Vứt, bỏ (rác)" },
            { kanji: "線", vietnamese: "TUYẾN", reading: "せん", meaning: "" },
            { kanji: "~番線", vietnamese: "PHIÊN TUYẾN", reading: "ばんせん", meaning: "Tuyến số..." },
            { kanji: "面", vietnamese: "DIỆN", reading: "めん", meaning: "" },
            { kanji: "全面", vietnamese: "TOÀN DIỆN", reading: "ぜんめん", meaning: "Toàn bộ, tất cả" },
            { kanji: "画面", vietnamese: "HỌA DIỆN", reading: "がめん", meaning: "Màn hình" },
            { kanji: "○○方面", vietnamese: "PHƯƠNG DIỆN", reading: "ほうめん", meaning: "Phương diện, phía, bề miền" },
            { kanji: "普", vietnamese: "PHỔ", reading: "ふ", meaning: "" },
            { kanji: "普通", vietnamese: "PHỔ THÔNG", reading: "ふつう", meaning: "Phổ thông, thông thường" },
            { kanji: "各", vietnamese: "CÁC", reading: "かく", meaning: "" },
            { kanji: "各駅", vietnamese: "CÁC DỊCH", reading: "かくえき", meaning: "Mỗi ga, các ga" },
            { kanji: "各国", vietnamese: "CÁC QUỐC", reading: "かっこく", meaning: "Các nước" },
            { kanji: "各自", vietnamese: "CÁC TỰ", reading: "かくじ", meaning: "Mỗi cá nhân, mỗi cái riêng rẽ" },
            { kanji: "次", vietnamese: "THỨ", reading: "じ/つぎ", meaning: "" },
            { kanji: "目次", vietnamese: "MỤC THỨ", reading: "もくじ", meaning: "Mục lục" },
            { kanji: "次回", vietnamese: "THỨ HỒI", reading: "じかい", meaning: "Lần tới" },
            { kanji: "次", vietnamese: "THỨ", reading: "つぎ", meaning: "Tiếp theo" },
            { kanji: "快", vietnamese: "KHOÁI", reading: "かい", meaning: "" },
            { kanji: "快速", vietnamese: "KHOÁI TỐC", reading: "かいそく", meaning: "Nhanh chóng, cực nhanh" },
            { kanji: "速", vietnamese: "TỐC", reading: "そく/はやい", meaning: "" },
            { kanji: "高速道路", vietnamese: "CAO TỐC ĐẠO LỘ", reading: "こうそくどうろ", meaning: "Đường cao tốc" },
            { kanji: "速度", vietnamese: "TỐC ĐỘ", reading: "そくど", meaning: "Tốc độ" },
            { kanji: "速い", vietnamese: "TỐC", reading: "はやい", meaning: "Nhanh chóng" },
            { kanji: "過", vietnamese: "QUÁ/QUA", reading: "か/すぎる", meaning: "" },
            { kanji: "通過", vietnamese: "THÔNG QUA", reading: "つうか", meaning: "Thông qua, đi qua, quá cảnh" },
            { kanji: "過去", vietnamese: "QUÁ KHỨ", reading: "かこ", meaning: "Quá khứ" },
            { kanji: "過ぎる", vietnamese: "QUÁ", reading: "すぎる", meaning: "Quá mức, quá" },
            { kanji: "鉄", vietnamese: "THIẾT", reading: "てつ", meaning: "" },
            { kanji: "地下鉄", vietnamese: "ĐỊA HẠ THIẾT", reading: "ちかてつ", meaning: "Tàu điện ngầm" },
            { kanji: "鉄道", vietnamese: "THIẾT ĐẠO", reading: "てつどう", meaning: "Đường sắt" },
            { kanji: "指", vietnamese: "CHỈ", reading: "し/ゆび", meaning: "" },
            { kanji: "指定", vietnamese: "CHỈ ĐỊNH", reading: "してい", meaning: "Chỉ định, đặt" },
            { kanji: "指定席", vietnamese: "CHỈ ĐỊNH TỊCH", reading: "ていせき", meaning: "Ghế chỉ định, ghế đặt sẵn" },
            { kanji: "指", vietnamese: "CHỈ", reading: "ゆび", meaning: "Ngón tay" },
            { kanji: "指輪", vietnamese: "CHỈ LUÂN", reading: "ゆびわ", meaning: "Nhẫn" },
            { kanji: "定", vietnamese: "ĐỊNH", reading: "てい", meaning: "" },
            { kanji: "定休日", vietnamese: "ĐỊNH HƯU NHẬT", reading: "ていきゅうび", meaning: "Ngày nghỉ định kỳ, nghỉ có phép" },
            { kanji: "安定", vietnamese: "AN ĐỊNH", reading: "あんてい", meaning: "Ổn định" },
            { kanji: "不安定", vietnamese: "BẤT AN ĐỊNH", reading: "ふあんてい", meaning: "Không ổn định" },
            { kanji: "席", vietnamese: "TỊCH", reading: "せき", meaning: "" },
            { kanji: "席", vietnamese: "TỊCH", reading: "せき", meaning: "Ghế" },
            { kanji: "出席", vietnamese: "XUẤT TỊCH", reading: "しゅっせき", meaning: "Có mặt, tham dự" },
            { kanji: "欠席", vietnamese: "KHUYẾT TỊCH", reading: "けっせき", meaning: "Vắng mặt" },
            { kanji: "由", vietnamese: "DO", reading: "ゆう", meaning: "" },
            { kanji: "自由", vietnamese: "TỰ DO", reading: "じゆう", meaning: "Tự do" },
            { kanji: "自由席", vietnamese: "TỰ DO TỊCH", reading: "じゆうせき", meaning: "Ghế tự do" },
            { kanji: "理由", vietnamese: "LÝ DO", reading: "りゆう", meaning: "Lý do" },
            { kanji: "番", vietnamese: "PHIÊN", reading: "ばん", meaning: "" },
            { kanji: "番号", vietnamese: "PHIÊN HIỆU", reading: "ばんごう", meaning: "Số hiệu, số" },
            { kanji: "~番", vietnamese: "PHIÊN", reading: "ばん", meaning: "Số (mấy)" },
            { kanji: "窓", vietnamese: "SONG", reading: "まど", meaning: "" },
            { kanji: "窓", vietnamese: "SONG", reading: "まど", meaning: "Cửa sổ" },
            { kanji: "窓口", vietnamese: "SONG KHẨU", reading: "まどぐち", meaning: "Cửa bán vé" },
            { kanji: "側", vietnamese: "TRẮC", reading: "がわ", meaning: "" },
            { kanji: "両側", vietnamese: "LƯỠNG TRẮC", reading: "りょうがわ", meaning: "Hai phía" },
            { kanji: "窓側", vietnamese: "SONG TRẮC", reading: "まどがわ", meaning: "Phía cửa sổ" },
            { kanji: "右側", vietnamese: "HỮU TRẮC", reading: "みぎがわ", meaning: "Phía bên phải" },
            { kanji: "路", vietnamese: "LỘ", reading: "ろ", meaning: "" },
            { kanji: "通路", vietnamese: "THÔNG LỘ", reading: "つうろ", meaning: "Đường đi, lối đi" },
            { kanji: "道路", vietnamese: "ĐẠO LỘ", reading: "どうろ", meaning: "Con đường" },
            { kanji: "線路", vietnamese: "TUYẾN LỘ", reading: "せんろ", meaning: "Tuyến đường xe lửa" },
            { kanji: "停", vietnamese: "ĐÌNH", reading: "てい", meaning: "" },
            { kanji: "停車", vietnamese: "ĐÌNH XA", reading: "ていしゃ", meaning: "Sự dừng xe" },
            { kanji: "バス停", vietnamese: "ĐÌNH", reading: "ばすてい", meaning: "Bến xe buýt" },
            { kanji: "整", vietnamese: "CHỈNH", reading: "せい", meaning: "" },
            { kanji: "整理", vietnamese: "CHỈNH LÝ", reading: "せいり", meaning: "Chỉnh lý" },
            { kanji: "整理券", vietnamese: "CHỈNH LÝ KHOÁN", reading: "せいりけん", meaning: "Vé đánh số" },
            { kanji: "券", vietnamese: "KHOÁN", reading: "けん", meaning: "" },
            { kanji: "駐車券", vietnamese: "TRÚ XA KHOÁN", reading: "ちゅうしゃけん", meaning: "Vé đỗ xe" },
            { kanji: "乗車券", vietnamese: "THỪA XA KHOÁN", reading: "じょうしゃけん", meaning: "Vé lên tàu xe" },
            { kanji: "回数券", vietnamese: "HỒI SỐ KHOÁN", reading: "かいすうけん", meaning: "Cuốn sổ vé, tập vé" },
            { kanji: "現", vietnamese: "HIỆN", reading: "げん/あらわれる", meaning: "" },
            { kanji: "現金", vietnamese: "HIỆN KIM", reading: "げんきん", meaning: "Tiền mặt" },
            { kanji: "表現", vietnamese: "BIỂU HIỆN", reading: "ひょうげん", meaning: "Biểu hiện, thể hiện" },
            { kanji: "現れる", vietnamese: "HIỆN", reading: "あらわれる", meaning: "Ló dạng, xuất hiện" },
            { kanji: "両", vietnamese: "LƯỠNG", reading: "りょう", meaning: "" },
            { kanji: "両親", vietnamese: "LƯỠNG THÂN", reading: "りょうしん", meaning: "Ba mẹ" },
            { kanji: "~両", vietnamese: "LƯỠNG", reading: "りょう", meaning: "~xe trên chuyến xe lửa, (toa)xe..." },
            { kanji: "替", vietnamese: "THẾ", reading: "かえる", meaning: "" },
            { kanji: "取り替える", vietnamese: "THỦ THẾ", reading: "とりかえる", meaning: "Đổi" },
            { kanji: "両替", vietnamese: "LƯỠNG THẾ", reading: "りょうがえ", meaning: "Đổi tiền" },
            { kanji: "着替える", vietnamese: "TRƯỚC THẾ", reading: "きがえる", meaning: "Thay quần áo" },
            { kanji: "優", vietnamese: "ƯU", reading: "ゆう/やさしい", meaning: "" },
            { kanji: "優先席", vietnamese: "ƯU TIÊN TỊCH", reading: "ゆうせんせき", meaning: "Ghế ưu tiên" },
            { kanji: "女優", vietnamese: "NỮ ƯU", reading: "じょゆう", meaning: "Nữ diễn viên" },
            { kanji: "優しい", vietnamese: "ƯU", reading: "やさしい", meaning: "Dịu dàng" },
            { kanji: "座", vietnamese: "TỌA", reading: "ざ/すわる", meaning: "" },
            { kanji: "座席", vietnamese: "TỌA TỊCH", reading: "ざせき", meaning: "Ghế ngồi" },
            { kanji: "正座", vietnamese: "CHÍNH TỌA", reading: "せいざ", meaning: "Ngồi ngay ngắn kiểu Nhật" },
            { kanji: "座る", vietnamese: "TỌA", reading: "すわる", meaning: "Ngồi" },
            { kanji: "降", vietnamese: "GIÁNG/HÀNG", reading: "こう/ふる/おりる", meaning: "" },
            { kanji: "降車口", vietnamese: "GIÁNG XA KHẨU", reading: "こうしゃぐち", meaning: "Lối ra khỏi xe, xuống xe" },
            { kanji: "以降", vietnamese: "DĨ GIÁNG", reading: "いこう", meaning: "Sau~" },
            { kanji: "降りる", vietnamese: "GIÁNG", reading: "おりる", meaning: "Xuống khỏi (xe, tàu)" },
            { kanji: "降る", vietnamese: "GIÁNG", reading: "ふる", meaning: "Rơi xuống" },
            { kanji: "準", vietnamese: "CHUẨN", reading: "じゅん", meaning: "" },
            { kanji: "準備", vietnamese: "CHUẨN BỊ", reading: "じゅんび", meaning: "Chuẩn bị" },
            { kanji: "備", vietnamese: "BỊ", reading: "び/そなえる", meaning: "" },
            { kanji: "備える", vietnamese: "BỊ", reading: "そなえる", meaning: "Chuẩn bị" },
            { kanji: "営", vietnamese: "DOANH", reading: "えい", meaning: "" },
            { kanji: "営業", vietnamese: "DOANH NGHIỆP", reading: "えいぎょう", meaning: "Kinh doanh, doanh nghiệp" },
            { kanji: "閉", vietnamese: "BẾ", reading: "へい/しまる/しめる", meaning: "" },
            { kanji: "開閉", vietnamese: "KHAI BẾ", reading: "かいへい", meaning: "Mở và đóng" },
            { kanji: "閉まる", vietnamese: "BẾ", reading: "しまる", meaning: "Đóng (tự động từ)" },
            { kanji: "閉める", vietnamese: "BẾ", reading: "しめる", meaning: "Đóng (tha động từ)" },
            { kanji: "案", vietnamese: "ÁN", reading: "あん", meaning: "" },
            { kanji: "案内", vietnamese: "ÁN NỘI", reading: "あんない", meaning: "Hướng dẫn, thông tin" },
            { kanji: "案", vietnamese: "ÁN", reading: "あん", meaning: "Đề án, đề nghị" },
            { kanji: "内", vietnamese: "NỘI", reading: "ない/うち", meaning: "" },
            { kanji: "家内", vietnamese: "GIA NỘI", reading: "かない", meaning: "Vợ" },
            { kanji: "以内", vietnamese: "DĨ NỘI", reading: "いない", meaning: "Trong vòng" },
            { kanji: "内側", vietnamese: "NỘI TRẮC", reading: "うちがわ", meaning: "Phía trong" },
            { kanji: "国内", vietnamese: "QUỐC NỘI", reading: "こくない", meaning: "Trong nước" },
            { kanji: "予", vietnamese: "DỰ", reading: "よ", meaning: "" },
            { kanji: "予定", vietnamese: "DỰ ĐỊNH", reading: "よてい", meaning: "Dự định" },
            { kanji: "予習", vietnamese: "DỰ TẬP", reading: "よしゅう", meaning: "Học trước bài, chuẩn bị trước" },
            { kanji: "約", vietnamese: "ƯỚC", reading: "やく", meaning: "" },
            { kanji: "予約", vietnamese: "DỰ ƯỚC", reading: "よやく", meaning: "Cuộc hẹn, đặt trước" },
            { kanji: "約~", vietnamese: "ƯỚC", reading: "やく", meaning: "Khoảng, ước chừng ~" },
            { kanji: "煙", vietnamese: "YÊN", reading: "えん/けむり", meaning: "" },
            { kanji: "禁煙", vietnamese: "CẤM YÊN", reading: "きんえん", meaning: "Cấm hút thuốc" },
            { kanji: "煙", vietnamese: "YÊN", reading: "けむり", meaning: "Khói" },
            { kanji: "当", vietnamese: "ĐƯƠNG", reading: "とう/あたる", meaning: "" },
            { kanji: "本当", vietnamese: "BẢN ĐƯƠNG", reading: "ほんとう", meaning: "Thật, sự thật" },
            { kanji: "当たる", vietnamese: "ĐƯƠNG", reading: "あたる", meaning: "Trúng, đúng" },
            { kanji: "当たり前", vietnamese: "ĐƯƠNG TIỀN", reading: "あたりまえ", meaning: "Đương nhiên là" },
            { kanji: "全", vietnamese: "TOÀN", reading: "ぜん", meaning: "" },
            { kanji: "全部", vietnamese: "TOÀN BỘ", reading: "ぜんぶ", meaning: "Toàn bộ" },
            { kanji: "全席", vietnamese: "TOÀN TỊCH", reading: "ぜんせき", meaning: "Toàn bộ ghế" },
            { kanji: "安全", vietnamese: "AN TOÀN", reading: "あんぜん", meaning: "An toàn" },
            { kanji: "客", vietnamese: "KHÁCH", reading: "きゃく", meaning: "" },
            { kanji: "客", vietnamese: "KHÁCH", reading: "きゃく", meaning: "Khách" },
            { kanji: "お客様", vietnamese: "KHÁCH DẠNG", reading: "おきゃくさま", meaning: "Quý khách" },
            { kanji: "様", vietnamese: "DẠNG", reading: "さま", meaning: "" },
            { kanji: "様子", vietnamese: "DẠNG TỬ", reading: "ようす", meaning: "Bộ dạng, tình trạng" },
            { kanji: "○○様", vietnamese: "DẠNG", reading: "さま", meaning: "Ngài ~" },
            { kanji: "解", vietnamese: "GIẢI", reading: "かい", meaning: "" },
            { kanji: "理解", vietnamese: "LÝ GIẢI", reading: "りかい", meaning: "Hiểu" },
            { kanji: "解説", vietnamese: "GIẢI THUYẾT", reading: "かいせつ", meaning: "Sự giải thích" },
            { kanji: "解答", vietnamese: "GIẢI ĐÁP", reading: "かいとう", meaning: "Đáp án" },
            { kanji: "分解", vietnamese: "PHÂN GIẢI", reading: "ぶんかい", meaning: "Tháo rời, tách rời" },
            { kanji: "協", vietnamese: "HIỆP", reading: "きょう", meaning: "" },
            { kanji: "協力", vietnamese: "HIỆP LỰC", reading: "きょうりょく", meaning: "Hợp tác, cộng tác" },
            { kanji: "願", vietnamese: "NGUYỆN", reading: "ねがう", meaning: "" },
            { kanji: "願う", vietnamese: "NGUYỆN", reading: "ねがう", meaning: "Cầu nguyện" },
            { kanji: "観", vietnamese: "QUAN", reading: "かん", meaning: "" },
            { kanji: "観光", vietnamese: "QUAN QUANG", reading: "かんこう", meaning: "Tham quan" },
            { kanji: "観客", vietnamese: "QUAN KHÁCH", reading: "かんきゃく", meaning: "Quan khách, người tham quan, du lịch" },
            { kanji: "園", vietnamese: "VIÊN", reading: "えん", meaning: "" },
            { kanji: "動物園", vietnamese: "ĐỘNG VẬT VIÊN", reading: "どうぶつえん", meaning: "Sở thú" },
            { kanji: "港", vietnamese: "CẢNG", reading: "こう/みなと", meaning: "" },
            { kanji: "空港", vietnamese: "KHÔNG CẢNG", reading: "くうこう", meaning: "Sân bay" },
            { kanji: "○○港", vietnamese: "CẢNG", reading: "こう", meaning: "Cảng~" },
            { kanji: "港", vietnamese: "CẢNG", reading: "みなと", meaning: "Cảng" },
            { kanji: "遊", vietnamese: "DU", reading: "ゆう/あそぶ", meaning: "" },
            { kanji: "遊園地", vietnamese: "DU VIÊN ĐỊA", reading: "ゆうえんち", meaning: "Khu vui chơi" },
            { kanji: "遊ぶ", vietnamese: "DU", reading: "あそぶ", meaning: "Vui chơi, chơi" },
            { kanji: "美", vietnamese: "MỸ", reading: "び/うつくしい", meaning: "" },
            { kanji: "美術館", vietnamese: "MỸ THUẬT QUÁN", reading: "びじゅつかん", meaning: "Bảo tàng mỹ thuật" },
            { kanji: "美人", vietnamese: "MỸ NHÂN", reading: "びじん", meaning: "Mỹ nhân" },
            { kanji: "美しい", vietnamese: "MỸ", reading: "うつくしい", meaning: "Xinh đẹp" },
            { kanji: "術", vietnamese: "THUẬT", reading: "じゅつ", meaning: "" },
            { kanji: "美術", vietnamese: "MỸ THUẬT", reading: "びじゅつ", meaning: "Mỹ thuật" },
            { kanji: "技術", vietnamese: "KỸ THUẬT", reading: "ぎじゅつ", meaning: "Kỹ thuật" },
            { kanji: "手術", vietnamese: "THỦ THUẬT", reading: "しゅじゅつ", meaning: "Phẫu thuật" },
            { kanji: "神", vietnamese: "THẦN", reading: "かみ/しん/じん", meaning: "" },
            { kanji: "神社", vietnamese: "THẦN XÃ", reading: "じんじゃ", meaning: "Đền thờ" },
            { kanji: "神経質", vietnamese: "THẦN KINH CHẤT", reading: "しんけいしつ", meaning: "Nhạy cảm" },
            { kanji: "神様", vietnamese: "THẦN DẠNG", reading: "かみさま", meaning: "Thần, vị thần" },
            { kanji: "寺", vietnamese: "TỰ", reading: "じ/てら", meaning: "" },
            { kanji: "○○寺", vietnamese: "TỰ", reading: "じ", meaning: "Chùa~" },
            { kanji: "お寺", vietnamese: "TỰ", reading: "おてら", meaning: "Ngôi chùa" },
            { kanji: "役", vietnamese: "DỊCH", reading: "やく", meaning: "" },
            { kanji: "市役所", vietnamese: "THỊ DỊCH SỞ", reading: "しやくしょ", meaning: "Cơ quan hành chính" },
            { kanji: "役に立つ", vietnamese: "DỊCH LẬP", reading: "やくにたつ", meaning: "Có ích, có lợi" },
            { kanji: "役員", vietnamese: "DỊCH VIÊN", reading: "やくいん", meaning: "Viên chức, cán bộ" },
            { kanji: "郵", vietnamese: "BƯU", reading: "ゆう", meaning: "" },
            { kanji: "郵便", vietnamese: "BƯU TIỆN", reading: "ゆうびん", meaning: "Bưu điện, dịch vụ bưu điện" },
            { kanji: "局", vietnamese: "CỤC", reading: "きょく", meaning: "" },
            { kanji: "郵便局", vietnamese: "BƯU TIỆN CỤC", reading: "ゆうびんきょく", meaning: "Bưu điện, bưu cục" },
            { kanji: "薬局", vietnamese: "DƯỢC CỤC", reading: "やっきょく", meaning: "Nhà thuốc" },
            { kanji: "交", vietnamese: "GIAO", reading: "こう", meaning: "" },
            { kanji: "交番", vietnamese: "GIAO PHIÊN", reading: "こうばん", meaning: "Đồn cảnh sát" },
            { kanji: "交通", vietnamese: "GIAO THÔNG", reading: "こうつう", meaning: "Giao thông" },
            { kanji: "交換", vietnamese: "GIAO HOÁN", reading: "こうかん", meaning: "Trao đổi, đổi" },
            { kanji: "差", vietnamese: "SAI", reading: "さ/さし", meaning: "" },
            { kanji: "差", vietnamese: "SAI", reading: "さ", meaning: "Khoảng cách, sự khác biệt" },
            { kanji: "差し出す", vietnamese: "SAI", reading: "さしだす", meaning: "Đưa ra, vươn ra" },
            { kanji: "差出人", vietnamese: "SAI", reading: "さしだしにん", meaning: "Người gửi" },
            { kanji: "点", vietnamese: "ĐIỂM", reading: "てん", meaning: "" },
            { kanji: "交差点", vietnamese: "GIAO SAI ĐIỂM", reading: "こうさてん", meaning: "Ngã tư" },
            { kanji: "点数", vietnamese: "ĐIỂM SỐ", reading: "てんすう", meaning: "Điểm số" },
            { kanji: "~点", vietnamese: "ĐIỂM", reading: "てん", meaning: "Điểm" },
            { kanji: "橋", vietnamese: "KIỀU", reading: "はし/きょう", meaning: "" },
            { kanji: "歩道橋", vietnamese: "BỘ ĐẠO KIỀU", reading: "ほどうきょう", meaning: "Cầu đi bộ, cầu vượt" },
            { kanji: "橋", vietnamese: "KIỀU", reading: "はし", meaning: "Cầu" },
            { kanji: "公", vietnamese: "CÔNG", reading: "こう", meaning: "" },
            { kanji: "公園", vietnamese: "CÔNG VIÊN", reading: "こうえん", meaning: "Công viên" },
            { kanji: "受", vietnamese: "THỤ", reading: "じゅ/うける", meaning: "" },
            { kanji: "受信", vietnamese: "THỤ TÍN", reading: "じゅしん", meaning: "Nhận (tin, email...)" },
            { kanji: "受験", vietnamese: "THỤ NGHIỆM", reading: "じゅけん", meaning: "Tham dự thi" },
            { kanji: "受ける", vietnamese: "THỤ", reading: "うける", meaning: "Nhận" },
            { kanji: "付", vietnamese: "PHÓ", reading: "つく/つける", meaning: "" },
            { kanji: "付ける", vietnamese: "PHÓ", reading: "つける", meaning: "Gắn lên, đính lên (tha động từ)" },
            { kanji: "片付ける", vietnamese: "PHIẾN PHÓ", reading: "かたづける", meaning: "Dọn dẹp" },
            { kanji: "受付", vietnamese: "THỤ PHÓ", reading: "うけつけ", meaning: "Tiếp tân" },
            { kanji: "付く", vietnamese: "PHÓ", reading: "つく", meaning: "Dính (tự động từ)" },
            { kanji: "科", vietnamese: "KHOA", reading: "か", meaning: "" },
            { kanji: "科学", vietnamese: "KHOA HỌC", reading: "かがく", meaning: "Khoa học" },
            { kanji: "外科", vietnamese: "NGOẠI KHOA", reading: "げか", meaning: "Ngoại khoa" },
            { kanji: "内科", vietnamese: "NỘI KHOA", reading: "ないか", meaning: "Nội khoa" },
            { kanji: "教科書", vietnamese: "GIÁO KHOA THƯ", reading: "きょうかしょ", meaning: "Sách giáo khoa" },
            { kanji: "鼻", vietnamese: "TỴ", reading: "はな/び", meaning: "" },
            { kanji: "耳鼻科", vietnamese: "NHĨ TỲ KHOA", reading: "じびか", meaning: "Khoa tai mũi họng" },
            { kanji: "鼻", vietnamese: "TỴ", reading: "はな", meaning: "Mũi" },
            { kanji: "婦", vietnamese: "PHỤ", reading: "ふ", meaning: "" },
            { kanji: "婦人", vietnamese: "PHỤ NHÂN", reading: "ふじん", meaning: "Phụ nữ" },
            { kanji: "産婦人科", vietnamese: "SẢN PHỤ NHÂN KHOA", reading: "さんふじんか", meaning: "Khoa sản phụ" },
            { kanji: "主婦", vietnamese: "CHỦ PHỤ", reading: "しゅふ", meaning: "Vợ" },
            { kanji: "形", vietnamese: "HÌNH", reading: "けい/ぎょう/かたち", meaning: "" },
            { kanji: "形式", vietnamese: "HÌNH THỨC", reading: "けいしき", meaning: "Hình thức" },
            { kanji: "図形", vietnamese: "ĐỒ HÌNH", reading: "ずけい", meaning: "Đồ thị, đồ hình, hình vẽ" },
            { kanji: "整形外科", vietnamese: "CHỈNH HÌNH NGOẠI KHOA", reading: "せいけいげか", meaning: "Khoa chỉnh hình" },
            { kanji: "人形", vietnamese: "NHÂN HÌNH", reading: "にんぎょう", meaning: "Búp bê" },
            { kanji: "形", vietnamese: "HÌNH", reading: "かたち", meaning: "Hình dạng" },
            { kanji: "骨", vietnamese: "CỐT", reading: "こつ/ほね", meaning: "" },
            { kanji: "骨折", vietnamese: "CỐT CHIẾT", reading: "こっせつ", meaning: "Gãy xương" },
            { kanji: "骨", vietnamese: "CỐT", reading: "ほね", meaning: "Xương" },
            { kanji: "折", vietnamese: "CHIẾT", reading: "せつ/おる", meaning: "" },
            { kanji: "右折", vietnamese: "HỮU CHIẾT", reading: "うせつ", meaning: "Rẽ phải" },
            { kanji: "左折", vietnamese: "TẢ CHIẾT", reading: "させつ", meaning: "Rẽ trái" },
            { kanji: "折る", vietnamese: "CHIẾT", reading: "おる", meaning: "Bẻ, gấp (tha động từ)" },
            { kanji: "折り紙", vietnamese: "CHIẾT CHỈ", reading: "おりがみ", meaning: "Môn gấp giấy" },
            { kanji: "折れる", vietnamese: "CHIẾT", reading: "おれる", meaning: "Bị bẻ, gấp (tự động từ)" },
            { kanji: "困", vietnamese: "KHỐN", reading: "こまる", meaning: "" },
            { kanji: "困る", vietnamese: "KHỐN", reading: "こまる", meaning: "Khốn khó, khổ cực" },
            { kanji: "消", vietnamese: "TIÊU", reading: "しょう/きえる/ける", meaning: "" },
            { kanji: "消す", vietnamese: "TIÊU", reading: "けす", meaning: "Dập tắt, xóa (tha động từ)" },
            { kanji: "消防", vietnamese: "TIÊU PHÒNG", reading: "しょうぼう", meaning: "Phòng cháy, cứu hỏa" },
            { kanji: "消える", vietnamese: "TIÊU", reading: "きえる", meaning: "Bị xóa, bị dập (tự động từ)" },
            { kanji: "消しゴム", vietnamese: "TIÊU", reading: "けしごむ", meaning: "Cục tẩy" },
            { kanji: "防", vietnamese: "PHÒNG", reading: "ぼう/ふせぐ", meaning: "" },
            { kanji: "予防", vietnamese: "DỰ PHÒNG", reading: "よぼう", meaning: "Dự phòng" },
            { kanji: "防ぐ", vietnamese: "PHÒNG", reading: "ふせぐ", meaning: "Đề phòng, ngăn chặn" },
            { kanji: "救", vietnamese: "CỨU", reading: "きゅう/すくう", meaning: "" },
            { kanji: "救急車", vietnamese: "CỨU CẤP XA", reading: "きゅうきゅうしゃ", meaning: "Xe cứu thương" },
            { kanji: "救う", vietnamese: "CỨU", reading: "すくう", meaning: "Cứu giúp" },
            { kanji: "警", vietnamese: "CẢNH", reading: "けい", meaning: "" },
            { kanji: "警官", vietnamese: "CẢNH QUAN", reading: "けいかん", meaning: "Cảnh sát viên" },
            { kanji: "察", vietnamese: "SÁT", reading: "さつ", meaning: "" },
            { kanji: "警察", vietnamese: "CẢNH SÁT", reading: "けいさつ", meaning: "Cảnh sát" },
            { kanji: "警察署", vietnamese: "CẢNH SÁT THỰ", reading: "けいさつしょ", meaning: "Sở cảnh sát" },
            { kanji: "故", vietnamese: "CỐ", reading: "こ", meaning: "" },
            { kanji: "事故", vietnamese: "SỰ CỐ", reading: "じこ", meaning: "Sự cố, tai nạn" },
            { kanji: "故障", vietnamese: "CỐ CHƯỚNG", reading: "こしょう", meaning: "Sự hỏng hóc, trục trặc" },
            { kanji: "故○○", vietnamese: "CỐ", reading: "こ", meaning: "(Tên Người)...quá cố" },
            { kanji: "伝", vietnamese: "TRUYỀN", reading: "でん/つたえる", meaning: "" },
            { kanji: "伝言", vietnamese: "TRUYỀN NGÔN", reading: "でんごん", meaning: "Tin nhắn, lời nhắn" },
            { kanji: "伝える", vietnamese: "TRUYỀN", reading: "つたえる", meaning: "Truyền đạt" },
            { kanji: "手伝う", vietnamese: "THỦ TRUYỀN", reading: "てつだう", meaning: "Giúp đỡ" },
            { kanji: "要", vietnamese: "YẾU", reading: "よう/いる", meaning: "" },
            { kanji: "必要", vietnamese: "TẤT YẾU", reading: "ひつよう", meaning: "Cần thiết" },
            { kanji: "要る", vietnamese: "YẾU", reading: "いる", meaning: "Cần" },
            { kanji: "重要", vietnamese: "TRỌNG YẾU", reading: "じゅうよう", meaning: "Quan trọng" },
            { kanji: "冷", vietnamese: "LÃNH", reading: "れい/つめたい/ひやす/ひえる/さめる/さます", meaning: "" },
            { kanji: "冷房", vietnamese: "LÃNH PHÒNG", reading: "れいぼう", meaning: "Máy lạnh" },
            { kanji: "冷たい", vietnamese: "LÃNH", reading: "つめたい", meaning: "Lạnh" },
            { kanji: "冷やす", vietnamese: "LÃNH", reading: "ひやす", meaning: "Làm lạnh (tha động từ)" },
            { kanji: "冷える", vietnamese: "LÃNH", reading: "ひえる", meaning: "Trở nên lạnh (tự động từ)" },
            { kanji: "冷める", vietnamese: "LÃNH", reading: "さめる", meaning: "Lạnh xuống (tự động từ)" },
            { kanji: "冷ます", vietnamese: "LÃNH", reading: "さます", meaning: "Làm lạnh (tha động từ)" },
            { kanji: "凍", vietnamese: "ĐÔNG", reading: "とう/こおる", meaning: "" },
            { kanji: "冷凍庫", vietnamese: "LÃNH ĐÔNG KHỐ", reading: "れいとうこ", meaning: "Tủ làm lạnh, tủ đá" },
            { kanji: "凍る", vietnamese: "ĐÔNG", reading: "こおる", meaning: "Làm đông đá" },
            { kanji: "庫", vietnamese: "KHỐ", reading: "こ", meaning: "" },
            { kanji: "金庫", vietnamese: "KIM KHỐ", reading: "きんこ", meaning: "Ngân khố, kho báu" },
            { kanji: "車庫", vietnamese: "XA KHỐ", reading: "しゃこ", meaning: "Nhà để xe" },
            { kanji: "召", vietnamese: "TRIỆU", reading: "めす", meaning: "" },
            { kanji: "召し上がる", vietnamese: "TRIỆU THƯỢNG", reading: "めしあがる", meaning: "Ăn (lịch sự)" },
            { kanji: "保", vietnamese: "BẢO", reading: "ほ", meaning: "" },
            { kanji: "保存する", vietnamese: "BẢO TỒN", reading: "ほぞんする", meaning: "Bảo tồn, cất trữ, lưu trữ" },
            { kanji: "存", vietnamese: "TỒN", reading: "ぞん", meaning: "" },
            { kanji: "ご存じです", vietnamese: "TỒN", reading: "ごぞんじです", meaning: "Biết (trang trọng)" },
            { kanji: "存じません", vietnamese: "TỒN", reading: "ぞんじません", meaning: "Tôi không biết" },
            { kanji: "必", vietnamese: "TẤT", reading: "ひつ/かならず", meaning: "" },
            { kanji: "必死", vietnamese: "TẤT TỬ", reading: "ひっし", meaning: "Quyết tâm" },
            { kanji: "必ず", vietnamese: "TẤT", reading: "かならず", meaning: "Chắc chắn, luôn luôn" },
            { kanji: "蔵", vietnamese: "TÀN", reading: "ぞう", meaning: "" },
            { kanji: "冷蔵庫", vietnamese: "LÃNH TÀN KHỐ", reading: "れいぞうこ", meaning: "Tủ lạnh" },
            { kanji: "費", vietnamese: "PHÍ", reading: "ひ", meaning: "" },
            { kanji: "費用", vietnamese: "PHÍ DỤNG", reading: "ひよう", meaning: "Chi phí" },
            { kanji: "消費者", vietnamese: "TIÊU PHÍ GIẢ", reading: "しょうひしゃ", meaning: "Người tiêu dùng" },
            { kanji: "旅費", vietnamese: "LỮ PHÍ", reading: "りょひ", meaning: "Chi phí du lịch" },
            { kanji: "会費", vietnamese: "HỘI PHÍ", reading: "かいひ", meaning: "Hội phí" },
            { kanji: "期", vietnamese: "KỲ", reading: "き", meaning: "" },
            { kanji: "期間", vietnamese: "KỲ GIAN", reading: "きかん", meaning: "Khoảng thời gian" },
            { kanji: "定期券", vietnamese: "ĐỊNH KỲ KHOÁN", reading: "ていきけん", meaning: "Vé định kỳ" },
            { kanji: "長期", vietnamese: "TRƯỜNG KỲ", reading: "ちょうき", meaning: "Thời kỳ dài" },
            { kanji: "短期", vietnamese: "ĐOẢN KỲ", reading: "たんき", meaning: "Thời kỳ ngắn" },
            { kanji: "限", vietnamese: "HẠN", reading: "げん/かぎる", meaning: "" },
            { kanji: "期限", vietnamese: "KỲ HẠN", reading: "きげん", meaning: "Kỳ hạn" },
            { kanji: "限度", vietnamese: "HẠN ĐỘ", reading: "げんど", meaning: "Giới hạn" },
            { kanji: "限る", vietnamese: "HẠN", reading: "かぎる", meaning: "Giới hạn" },
            { kanji: "限定", vietnamese: "HẠN ĐỊNH", reading: "げんてい", meaning: "Hạn định" },
            { kanji: "製", vietnamese: "CHẾ", reading: "せい", meaning: "" },
            { kanji: "~製", vietnamese: "CHẾ", reading: "せい", meaning: "Làm tại, ở" },
            { kanji: "製品", vietnamese: "CHẾ PHẨM", reading: "せいひん", meaning: "Sản phẩm" },
            { kanji: "造", vietnamese: "TẠO", reading: "ぞう/つくる", meaning: "" },
            { kanji: "製造", vietnamese: "CHẾ TẠO", reading: "せいぞう", meaning: "Chế tạo, làm ra" },
            { kanji: "造る", vietnamese: "TẠO", reading: "つくる", meaning: "Chế tạo, làm ra" },
            { kanji: "賞", vietnamese: "THƯỞNG", reading: "しょう", meaning: "" },
            { kanji: "賞", vietnamese: "THƯỞNG", reading: "しょう", meaning: "Giải thưởng, phần thưởng" },
            { kanji: "賞味期限", vietnamese: "THƯỞNG VỊ KỲ HẠN", reading: "しょうみきげん", meaning: "Kỳ hạn sử dụng tốt nhất" },
            { kanji: "賞金", vietnamese: "THƯỞNG KIM", reading: "しょうきん", meaning: "Tiền thưởng" },
            { kanji: "賞品", vietnamese: "THƯỞNG PHẨM", reading: "しょうひん", meaning: "Sản phẩm thưởng, giải thưởng" },
            { kanji: "法", vietnamese: "PHÁP", reading: "ほう", meaning: "" },
            { kanji: "方法", vietnamese: "PHƯƠNG PHÁP", reading: "ほうほう", meaning: "Phương pháp" },
            { kanji: "文法", vietnamese: "VĂN PHÁP", reading: "ぶんぽう", meaning: "Văn phạm" },
            { kanji: "温", vietnamese: "ÔN", reading: "おん/あたたかい", meaning: "" },
            { kanji: "温度", vietnamese: "ÔN ĐỘ", reading: "おんど", meaning: "Nhiệt độ" },
            { kanji: "気温", vietnamese: "KHÍ ÔN", reading: "きおん", meaning: "Nhiệt độ" },
            { kanji: "温かい", vietnamese: "ÔN", reading: "あたたかい", meaning: "Ấm" },
            { kanji: "常温", vietnamese: "THƯỜNG ÔN", reading: "じょうおん", meaning: "Nhiệt độ thông thường" },
            { kanji: "材", vietnamese: "TÀI", reading: "ざい", meaning: "" },
            { kanji: "材料", vietnamese: "TÀI LIỆU", reading: "ざいりょう", meaning: "Tài liệu, vật liệu" },
            { kanji: "教材", vietnamese: "GIÁO TÀI", reading: "きょうざい", meaning: "Tài liệu giảng dạy" },
            { kanji: "卵", vietnamese: "NOÃN", reading: "たまご", meaning: "" },
            { kanji: "卵", vietnamese: "NOÃN", reading: "たまご", meaning: "Trứng" },
            { kanji: "卵焼き", vietnamese: "NOÃN THIÊU", reading: "たまごやき", meaning: "Trứng chiên" },
            { kanji: "乳", vietnamese: "NHŨ", reading: "にゅう", meaning: "" },
            { kanji: "牛乳", vietnamese: "NGƯU NHŨ", reading: "ぎゅうにゅう", meaning: "Sữa" },
            { kanji: "粉", vietnamese: "PHẤN", reading: "こな/こ", meaning: "" },
            { kanji: "粉", vietnamese: "PHẤN", reading: "こな", meaning: "Bột mì, bột" },
            { kanji: "小麦粉", vietnamese: "TIỂU MẠCH PHẤN", reading: "こむぎこ", meaning: "Bột mì" },
            { kanji: "袋", vietnamese: "ĐẠI", reading: "ふくろ", meaning: "" },
            { kanji: "袋", vietnamese: "ĐẠI", reading: "ふくろ", meaning: "Túi, bao" },
            { kanji: "紙袋", vietnamese: "CHỈ ĐẠI", reading: "かみぶくろ", meaning: "Túi giấy, bao giấy" },
            { kanji: "ごみ袋", vietnamese: "ĐẠI", reading: "ごみぶくろ", meaning: "Túi rác, bao rác" },
            { kanji: "手袋", vietnamese: "THỦ ĐẠI", reading: "てぶくろ", meaning: "Găng tay" },
            { kanji: "○足袋", vietnamese: "TÚC ĐẠI", reading: "たび", meaning: "Vớ (dùng khi mặc kimono)" },
            { kanji: "混", vietnamese: "HỖN", reading: "こん/まぜる", meaning: "" },
            { kanji: "混雑", vietnamese: "HỖN TẠP", reading: "こんざつ", meaning: "Tắc nghẽn, đông đúc" },
            { kanji: "混ぜる", vietnamese: "HỖN", reading: "まぜる", meaning: "Trộn" },
            { kanji: "焼", vietnamese: "THIÊU", reading: "やく/やける", meaning: "" },
            { kanji: "焼く", vietnamese: "THIÊU", reading: "やく", meaning: "Nướng, rán (tha động từ)" },
            { kanji: "焼ける", vietnamese: "THIÊU", reading: "やける", meaning: "Bị nướng, được nướng (tự động từ)" },
            { kanji: "表", vietnamese: "BIỂU", reading: "ひょう/おもて/あらわす", meaning: "" },
            { kanji: "表", vietnamese: "BIỂU", reading: "おもて", meaning: "Bên ngoài, mặt ngoài" },
            { kanji: "表面", vietnamese: "BIỂU DIỆN", reading: "ひょうめん", meaning: "Bề mặt" },
            { kanji: "発表", vietnamese: "PHÁT BIỂU", reading: "はっぴょう", meaning: "Phát biểu" },
            { kanji: "代表", vietnamese: "ĐẠI BIỂU", reading: "だいひょう", meaning: "Đại biểu" },
            { kanji: "表す", vietnamese: "BIỂU", reading: "あらわす", meaning: "Thể hiện" },
            { kanji: "裏", vietnamese: "LÝ", reading: "うら", meaning: "" },
            { kanji: "裏", vietnamese: "LÝ", reading: "うら", meaning: "Bên trong, (bên trái)" },
            { kanji: "裏返す", vietnamese: "LÝ PHẢN", reading: "うらがえす", meaning: "Lật mặt trong ra" },
            { kanji: "留", vietnamese: "LƯU", reading: "りゅう/る/とめる", meaning: "" },
            { kanji: "留学", vietnamese: "LƯU HỌC", reading: "りゅうがく", meaning: "Du học" },
            { kanji: "留守番", vietnamese: "LƯU THỦ PHIÊN", reading: "るすばん", meaning: "Giữ nhà" },
            { kanji: "保留", vietnamese: "BẢO LƯU", reading: "ほりゅう", meaning: "Bảo lưu" },
            { kanji: "書留", vietnamese: "THƯ LƯU", reading: "かきとめ", meaning: "Thư bảo đảm" },
            { kanji: "守", vietnamese: "THỦ", reading: "しゅ/す/もる", meaning: "" },
            { kanji: "守備", vietnamese: "THỦ BỊ", reading: "しゅび", meaning: "Bảo vệ, phòng thủ" },
            { kanji: "留守", vietnamese: "LƯU THỦ", reading: "るす", meaning: "Vắng mặt" },
            { kanji: "守る", vietnamese: "THỦ", reading: "まもる", meaning: "Bảo vệ" },
            { kanji: "濃", vietnamese: "NỒNG", reading: "こい", meaning: "" },
            { kanji: "濃い", vietnamese: "NỒNG", reading: "こい", meaning: "Nồng, đậm" },
            { kanji: "薄", vietnamese: "BẠC", reading: "うすい", meaning: "" },
            { kanji: "薄い", vietnamese: "BẠC", reading: "うすい", meaning: "Lạt, nhạt" },
            { kanji: "部", vietnamese: "BỘ", reading: "ぶ", meaning: "" },
            { kanji: "部分", vietnamese: "BỘ PHẬN", reading: "ぶぶん", meaning: "Bộ phận" },
            { kanji: "学部", vietnamese: "HỌC BỘ", reading: "がくぶ", meaning: "Ngành học, khoa" },
            { kanji: "部長", vietnamese: "BỘ TRƯỞNG", reading: "ぶちょう", meaning: "Trưởng phòng" },
            { kanji: "部屋", vietnamese: "BỘ ỐC", reading: "へや", meaning: "Căn phòng" },
            { kanji: "数", vietnamese: "SỐ", reading: "すう/かず/かぞえる", meaning: "" },
            { kanji: "数字", vietnamese: "SỐ TỰ", reading: "すうじ", meaning: "Con số" },
            { kanji: "数学", vietnamese: "SỐ HỌC", reading: "すうがく", meaning: "Toán" },
            { kanji: "数", vietnamese: "SỐ", reading: "かず", meaning: "Số" },
            { kanji: "数える", vietnamese: "SỐ", reading: "かぞえる", meaning: "Đếm" },
            { kanji: "件", vietnamese: "KIỆN", reading: "けん", meaning: "" },
            { kanji: "件名", vietnamese: "KIỆN DANH", reading: "けんめい", meaning: "Tựa đề" }
        ];
